#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

get_changes () {
  git diff HEAD~1..HEAD~0 -- origin/main build src stories test "*.mjs" "*.cjs" "*.mts" "*.cts" "*.jsx"
}

has_changes () {
  [ ! -z "$(get_changes)" ]
}

get_package_dependencies_changes () {
  git diff HEAD~1..HEAD~0 -- origin/main package.json | grep \
    -e '+\s*\"shinkansen-cogs\":\s\".*"' \
    -e '+\s*\"shinkansen-gears\":\s\".*"' \
    -e '+\s*\"shinkansen-pantograph\":\s\".*"' \
    -e '+\s*\"shinkansen-pinion\":\s\".*"' \
    -e '+\s*\"shinkansen-rails\":\s\".*"' \
    -e '+\s*\"shinkansen-signals\":\s\".*"' \
    -e '+\s*\"shinkansen-sprockets\":\s\".*"' \
    -e '+\s*\"shinkansen-transmission\":\s\".*"'
}

has_package_dependencies_changes () {
  [ ! -z "$(get_package_dependencies_changes)" ]
}

if has_changes || has_package_dependencies_changes;
then
  npx cross-env DEBUG=@modernpoacher/hooks* node .husky/post-commit.mjs
fi
